version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    networks:
      - fullstack
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: mypassword
      DB_NAME: mydb
    networks:
      - fullstack
    ports:
      - 8080:8080

volumes:
  db-data:

networks:
  fullstack:
    driver: bridge